steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'my-app'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-app'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-app'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-app'

options:
  logging: CLOUD_LOGGING_ONLY
