steps:
  # Step 1: Build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/phaluuuuuu/my-app'
      - '.'

  # Step 2: Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/phaluuuuuu/my-app'

# Store build result
images:
  - 'gcr.io/phaluuuuuu/my-app'
